version: '3'

services:

  nginx: 
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - back
  
  back:
    restart: 'always'
    build: 
      context: .
      dockerfile: ./docker/back/Dockerfile
    entrypoint: /app/wsgi-entrypoint.sh
    expose:
      - 8000
